name: AutoComment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            üëã @{{ author }}
            Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
            Please make sure you have given us as much context as possible.
          pullRequestOpened: |
            ‚ö†Ô∏è ‚ö†Ô∏è ‚ö†Ô∏è

            üëã @{{ author }}
            Please remember that we use [**fast-forward merge**](https://git-scm.com/docs/git-merge#Documentation/git-merge.txt---ff-only) instead of using the usual *Create a merge commit*, *squash and merge* or *rebase and merge* for merging `develop` into `main` or vice versa.
            You can execute it by creating a new comment in this PR with the following content:
            ```
            fast-forward
            ```
            ***With an additional slash (`/`) before the command.***
            **Please create this comment only after all tests have been completed positively!**

            For merging your feature branch to `develop` please use [*squash and merge*](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits).

            Thanks! üôè
