name: PRCheck
on:
  pull_request_target:
    types: [opened, edited, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-check-main:
    name: Check PR (main)
    if: ${{ !startsWith(github.head_ref, 'release-please--branches--main') }}
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          if: ${{ github.base_ref == 'main' && github.head_ref != 'develop' }}
          comment: |
            ğŸš¨ ğŸš¨ ğŸš¨
            Merging the `${{ github.head_ref }}` branch into `main` is not allowed.
            Only `develop` (and release branches) can be merged into `main`.

            **This pull request will be closed**â—ï¸
  pr-check-gh-pages:
    name: Check PR (gh-pages)
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          if: ${{ github.base_ref == 'gh-pages' }}
          comment: |
            ğŸš¨ ğŸš¨ ğŸš¨
            No pull request are allowed to be merged into `gh-pages`.

            **This pull request will be closed**â—ï¸
