name: Testing

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and project
        run: |
          python -m pip install poetry==1.3.1
          poetry install --with test
      - name: Check with isort
        run: |
          poetry run isort --check-only .
      - name: Check with black
        run: |
          poetry run black --check ./src/sk_transformers  ./tests
      - name: Check with mypy
        run: |
          poetry run mypy --config-file=pyproject.toml .
      - name: Check with bandit
        run: |
          poetry run bandit -r ./src/sk_transformers/*
      - name: Lint with pylint
        run: |
          poetry run pylint --rcfile=pyproject.toml ./src/sk_transformers ./tests
      - name: Test with pytest
        run: |
          poetry run pytest --cov src/sk_transformers --cov-fail-under=90 --cov-report term-missing
